name: CI/CD - Build and Deploy WPF App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the WPF project
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Step 5: Publish the app
      - name: Publish the app
        run: dotnet publish --configuration Release --output ./publish

      # Step 6: Deploy using Native SSH
      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Install OpenSSH client
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

          # Use SCP to copy files to the server
          scp -P $env:SSH_PORT -r ./publish/* $env:SSH_USER@$env:SSH_HOST:/var/www/wpf-app

          # Connect via SSH and perform post-deployment tasks
          ssh -p $env:SSH_PORT $env:SSH_USER@$env:SSH_HOST << EOF
          echo "Deployment complete. Performing server-specific tasks..."
          # Example: Restarting a service
          # net stop MyService
          # net start MyService
          EOF
